overrides:
  ceph:
    conf:
      global:
        ms die on skipped message: false
tasks:
- install:
- ceph:
    fs: btrfs
- rbd:
    all:
      image_size: 20480
- workunit:
    clients:
      all:
        - suites/iozone.sh
